name: Deploy to AWS

on:
  workflow_dispatch

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger AWS Codepipeline
        env:
          AWS_region:
          aws_key_id:
          aws_secret_access_key:
        run: |
          aws codepipeline start-pipeline-execution --name <pip_name> --region $AWS_REGION
