name: Workflow test

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #Checkout the codebase
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run builds
      run: |
        mvn clean install -Dskiptests
        
