name: Workflow test

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #Checkout the codebase
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      env:
        cache-name: cache-maven
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
    - name: Build Java application with Maven
      run: mvn clean install -DskipTests

    - name: Build Docker Image
      run: |
        docker build -t 7990509979/demoProject .
        docker image ls
      
    - name: Push Docker image to Artifactory 
      run: |
        docker push 7990509979/demoProject
    
        
